### ISSUE TITLE
vcredist2005 fails with vcredist2005 8.0.50727.619501 edit failed

### ISSUE THREAD

**Issue by ImNtReal** [TheCakeIsNaOH/choco-remixer#1]
I've been able to successfully internalize the other vcredist packages with your tool, but 2005 is failing. Here are two attempts at it:
   JMPUGH@408ITSLT233  ~  Invoke-InternalizeChocoPkg -configXML .\choco-remixer\config.xml -internalizedXML .\choco-remixer\internalized.xml -repoCheckXML .\choco-remixer\repo-check.xml -skipRepoCheck
Found vcredist2005 8.0.50727.619501 to internalize
Starting vcredist2005
WARNING: vcredist2005 8.0.50727.619501 failed downloading or editing
WARNING: Error: You cannot call a method on a null-valued expression.
vcredist2005 8.0.50727.619501 edit failed
   JMPUGH@408ITSLT233  ~  Invoke-InternalizeChocoPkg -configXML .\choco-remixer\config.xml -internalizedXML .\choco-remixer\internalized.xml -repoCheckXML .\choco-remixer\repo-check.xml -skipRepoCheck -Verbose
VERBOSE: HEAD https://nexus.nghs.com/repository/nuget-hosted with 0-byte payload
VERBOSE: received 1952-byte response of content type text/html
VERBOSE: pushURL exists, but did not return ok. This is expected if it requires authentication and credentials are not provided
VERBOSE: HEAD https://community.chocolatey.org/api/v2/ with 0-byte payload
Exception: C:\Users\jmpugh\choco-remixer\choco-remixer\private\Test-Url.ps1:19
Line |
  19 |          Throw "bad $name in personal-packages.xml"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | bad publicRepoURL in personal-packages.xml

**Comment by TheCakeIsNaOH** [comment]
Looks like that package has been majorly revamped.
I've updated the convert function for it.
Closed with 2c851e5

**Comment by ImNtReal** [comment]
Thanks for the quick update. I was hoping I'd be able to get a PR together for you, but simply haven't had time to dig that far into it.
