### ISSUE TITLE
Firefox Locale package installation, repomove and credidentials

### ISSUE THREAD

**Issue by mengpo1** [TheCakeIsNaOH/choco-remixer#13]
Hi there,

Thanks very much for you work.

I installed choco-mixer and it is working great. Thanks !

I got three questions about it :

- When I tried to install a choco-mixer 's internalized firefox package, the main part is downloading but the nupkg has a helpers.ps1 which should download the locale package. And this one is not downloading. How can I edit the helpers.ps1 to download the locale package ? 
- we're using a Nexus Proxy and I wondered how does the repoMove part work ? As a matter fact, I did not find anything inside the nexus documentation. When I try to activate `<repoMove>yes</repoMove>` this inside the config.xml, I got an error 401. So I think I got something wrong... 
- For my information, if I have Creds for our proxy or repo, how can we setting this up inside the config.xml ? We can change to yes <proxyRepoCreds> but where can we specify the creds ? Inside the url ? Like this :<moveToRepoURL>http://user@password:X.X.X.X:XX/repository/chocolatey-hosted/</moveToRepoURL>

Thanks again very much and thanks in advance for your help,

**Comment by TheCakeIsNaOH** [comment]
> When I tried to install a choco-mixer 's internalized firefox package, the main part is downloading but the nupkg has a helpers.ps1 which should download the locale package. And this one is not downloading. How can I edit the helpers.ps1 to download the locale package ?

Currently, I have it set hardcoded to `en-US`:
https://github.com/TheCakeIsNaOH/choco-remixer/blob/29b07f963ec518bd0ba1195ccc220f2b9ccb7f43/choco-remixer/pkgs/PkgFunctions-install.ps1#L840

You could change that to the desired other locale you want. Or if you have a better way to pick the locale to use, I am open to pull requests.

> we're using a Nexus Proxy and I wondered how does the repoMove part work ? As a matter fact, I did not find anything inside the nexus documentation. When I try to activate <repoMove>yes</repoMove> this inside the config.xml, I got an error 401. So I think I got something wrong...

Make sure you have the `proxyRepoCreds` set with nexus credentials that have access to the nexus proxy repository (in the format `user:password`, and the `proxyRepoURL` and `moveToRepoURL` are set. If you are still getting an error, more detailed logs and information would be needed for me to help.

> For my information, if I have Creds for our proxy or repo, how can we setting this up inside the config.xml ? We can change to yes but where can we specify the creds ? Inside the url ? Like this :http://user@password:X.X.X.X:XX/repository/chocolatey-hosted/

Look at the configuration template: https://github.com/TheCakeIsNaOH/choco-remixer/blob/master/config.xml.template 

It is assumed that Chocolatey is already configured with Api key(s) for all urls used for pushing. So for the `pushUrl`, `privateRepoURL` and `moveToRepoURL` (which all could be the same repository, those three do not have to be different). Use the `choco apikey` command to set those API keys. See here for how to get a NuGet/Chocolatey API key from Nexus: https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/nuget-repositories/deploying-packages-to-nuget-hosted-repositories#DeployingPackagestoNuGetHostedRepositories-AccessingyourNuGetAPIKey

**Comment by mengpo1** [comment]
> Currently, I have it set hardcoded to `en-US`:
> 
> https://github.com/TheCakeIsNaOH/choco-remixer/blob/29b07f963ec518bd0ba1195ccc220f2b9ccb7f43/choco-remixer/pkgs/PkgFunctions-install.ps1#L840
> 
> You could change that to the desired other locale you want. Or if you have a better way to pick the locale to use, I am open to pull requests.

I changed the variable here and everything's working fine now, thanks ! Well, I'm not a programmer but is there any way to set the locale variable inside the config.xml ? It could be a easier to find and maybe you'd have to set it only once.

> Make sure you have the `proxyRepoCreds` set with nexus credentials that have access to the nexus proxy repository (in the format `user:password`, and the `proxyRepoURL` and `moveToRepoURL` are set. If you are still getting an error, more detailed logs and information would be needed for me to help.
> 
Everything was good here. The problem came from the creds. 

> Look at the configuration template: https://github.com/TheCakeIsNaOH/choco-remixer/blob/master/config.xml.template
> 
> It is assumed that Chocolatey is already configured with Api key(s) for all urls used for pushing. So for the `pushUrl`, `privateRepoURL` and `moveToRepoURL` (which all could be the same repository, those three do not have to be different). Use the `choco apikey` command to set those API keys. See here for how to get a NuGet/Chocolatey API key from Nexus: https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/nuget-repositories/deploying-packages-to-nuget-hosted-repositories#DeployingPackagestoNuGetHostedRepositories-AccessingyourNuGetAPIKey
 
Actually, it was simplier than I was expected. At first, I though that I had to put my creds like this: `<proxyRepoCreds>yes</proxyRepoCreds>` and then put the creds within the URL. But now I got it, it's: `<proxyRepoCreds>user:password</proxyRepoCreds>`. 
Sorry about that and thanks for your answer!

**Comment by TheCakeIsNaOH** [comment]
@mengpo1 If you pull down the latest update, I've added a config option to set the locale, let me know if that works for you.
