### ISSUE TITLE
PowerBI and microsoft-office-deployment request

### ISSUE THREAD

**Issue by rmusick** [TheCakeIsNaOH/choco-remixer#14]
Hi Could I request the following items to be added?
PowerBI:
I tried to internalize this on my own but kept getting an error.  Something is not liked in the packages.xml
microsoft-office-deployment:
This one is way over my head, but Microsoft keeps changing the link and the package breaks.
Thanks.

**Comment by TheCakeIsNaOH** [comment]
For `powerbi`, that `.nupkg` file is really weird, and required a change elsewhere for some reason. I've added it, if you pull the latest commit you should be able to internalize it. 

For `microsoft-office-deployment`, that is not one that can be properly internalized as is. Sure, I can internalize the initial `.exe` download, but that `.exe` then goes and downloads the rest of Office, but that depends on the configuration passed in via package parameters. So in terms of making a truly offline package, it probably would be easiest to manually download the appropriate offline office installer for your license, and create a separate package for that. If you just want internalization of that initial deployment `.exe`, I can add that, but it won't be a completely offline/internal package.

**Comment by rmusick** [comment]
Thanks for adding PowerBI, for Office, I'll do what is recommended.  
Thank your for taking the time to do this and for all the work you have done with this project,   It really has saved us a lot of time packaging software.

**Comment by TheCakeIsNaOH** [comment]
You may be able to use https://github.com/chocolatey-community/chocolatey-package-recipes/tree/master/office365-x64 as a basis for the internal office package. If you create a package that could be shared with the community, contributing back to that repository would be nice. 

> Thank your for taking the time to do this and for all the work you have done with this project, It really has saved us a lot of time packaging software.

You are very welcome.
