### ISSUE TITLE
nexus-repository 3.60.0.2 failed downloading or editing

### ISSUE THREAD

**Issue by tr9stan** [TheCakeIsNaOH/choco-remixer#17]
First time submitting an issue :)  I was trying to internalize "nexus-repository" and received the below error message. I have not made any changes to the original install script for nexus-repository.

WARNING: nexus-repository 3.60.0.2 failed downloading or editing
This is most likely caused by changes to the format of the install script
WARNING: Error details:
You cannot call a method on a null-valued expression.
    $fullurl32 = ($obj.installScriptOrig -split "`n" | Select-String -Pattern '\$url64\s+=').tostring()

at Convert-nexus-repository,
C:\Users\user\Documents\git-projects\choco-remixer\choco-remixer\pkgs\PkgFunctions-zip.ps1: line 327
at Invoke-InternalizeChocoPkg,
C:\Users\user\Documents\git-projects\choco-remixer\choco-remixer\public\Invoke-InternalizeChocoPkg.ps1: line 195
at <ScriptBlock>, <No file>: line 1
nexus-repository 3.60.0.2 edit failed

**Comment by TheCakeIsNaOH** [comment]
@tr9stan Looks like the updated nexus-repository script format finally got pushed. I've fixed the problem, try the latest commit.
