### ISSUE TITLE
Trouble pushing Internalized Packages on a Nexus Repo

### ISSUE THREAD

**Issue by mengpo1** [TheCakeIsNaOH/choco-remixer#20]
Hi there,

I'm currently using a Nexus repo with an apikey and when I try to push some packages I got a _400 Bad Request_ answer :
```
pushing adobereader
[NuGet] You are running the 'push' operation with an 'HTTP' source, 'http://XXX.XXX.XXX.XXX/repository/chocolatey-hosted/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
Response status code does not indicate success : 400 (Bad Request).

adobereader 2023.6.20320 push failed

```
The api key is set and the strange thing is that the packages are still pushed on the repo (and I can get them with my other chocolatey clients). 

I think the problem could be the nexus repo configuration but I'm not sure... What am I missing ? 

Thanks !

**Comment by TheCakeIsNaOH** [comment]
What happens if you run a manual `choco push --source="http://XXX.XXX.XXX.XXX/repository/chocolatey-hosted/"` with that package?

**Comment by mengpo1** [comment]
![screenshot_chocolatey](https://github.com/TheCakeIsNaOH/choco-remixer/assets/5934210/6655368b-0d88-4768-9d57-e02709e4d138)

Sorry for the quality...

**Comment by TheCakeIsNaOH** [comment]
That looks like a problem with the nexus server. If redeploy is disabled on that repository, does that version already exist? And what are the upload size limits on the repository, both in Nexus itself, and any reverse proxies or firewalls in front of it.
