### ISSUE TITLE
package: multicommander 

### ISSUE THREAD

**Issue by GertVanderstukken** [TheCakeIsNaOH/choco-remixer#25]
Hello all,

I am trying to internalize multicommander:
https://community.chocolatey.org/packages/MultiCommander

This is a "not-yet-implemented" package, so I added this to packages.xml:
(and removed "multicommander" from the notImplemented section off course)

    <pkg>
      <id>multicommander</id>
      <functionName>Convert-InstallChocolateyPackage</functionName>
      <needsStopAction>no</needsStopAction>
      <needsToolsDir>yes</needsToolsDir>
      <architecture>both</architecture>
      <urlType>0</urlType>
      <argsType>0</argsType>
      <removeEXE>yes</removeEXE>
      <doubleQuotesUrl>yes</doubleQuotesUrl>
      <checksumArgsType>5</checksumArgsType>
      <checksumTypeType>sha1</checksumTypeType>
      <whyNotInternal>ToDetermine</whyNotInternal>
    </pkg>

but it does not seem to work.
I get this error:

***
Found multicommander 13.5.0.2983 to internalize
Starting multicommander
WARNING: multicommander 13.5.0.2983 failed downloading or editing
This is most likely caused by changes to the format of the install script
WARNING: Error details:
You cannot call a method on a null-valued expression.
    $obj.installScriptMod = Edit-InstallChocolateyPackage @editInstallChocolateyPackageArgs

at Edit-InstallChocolateyPackage,
C:\Users\Administrator\Documents\choco-remixer\choco-remixer\public\Edit-InstallChocolateyPackage.ps1: line 42
at Convert-InstallChocolateyPackage,
C:\Users\Administrator\Documents\choco-remixer\choco-remixer\private\Convert-InstallChocolateyPackage.ps1: line 24
at Invoke-InternalizeDownloadedChocoPkg,
C:\Users\Administrator\Documents\choco-remixer\choco-remixer\public\Invoke-InternalizeDownloadedChocoPkg.ps1: line 141
at Invoke-InternalizeChocoPkg, C:\Users\Administrator\Documents\choco-remixer\choco-remixer\public\Invoke-InternalizeChocoPkg.ps1:
line 106
at <ScriptBlock>, <No file>: line 1
multicommander 13.5.0.2983 edit failed
***

This is my first attempt to add a package, so I might miss something obvious...
BTW: great tool !!!

**Comment by TheCakeIsNaOH** [comment]
It looks like it used tabs instead of spaces in the package script. I added another urlType to account for this. Otherwise, the xml is correct. It has been added in  a421b5a 

> BTW: great tool !!!

Thanks, I'm glad it's been useful to you.

**Comment by GertVanderstukken** [comment]
Nice!!!
Thanks for the fast action.

**Comment by GertVanderstukken** [comment]
I see you made a small (copy/paste) typo in ADDING_PACKAGES.md
The new option is also mentioned as type 8 instead of 9...

but don't worry: the world keeps on turning, even with that typo :)
