### ISSUE TITLE
Multicommander issue

### ISSUE THREAD

**Issue by GertVanderstukken** [TheCakeIsNaOH/choco-remixer#27]
It seems that the multicommander package is having an issue after internalization.

This is the content of the internalized chocolateyinstall.ps1:
```
$ErrorActionPreference = 'Stop'
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$packageArgs = @{
    file     = (Join-Path $toolsDir "MultiCommander_win32_(13.5.0.2983).exe")
    file64   = (Join-Path $toolsDir "MultiCommander_x64_(13.5.0.2983).exe")
	packageName    = 'multicommander'
	fileType       = 'exe'
	url            = "https://multicommander.com/files/updates/MultiCommander_win32_(13.5.0.2983).exe"
	url64bit       = "https://multicommander.com/files/updates/MultiCommander_x64_(13.5.0.2983).exe"
	softwareName   = 'MultiCommander'
	checksum       = 'C720B9FB9924E8887EA9B1D7BAC43ED3C5EC3839'
	checksumType   = 'sha1'
	checksum64     = '4F14D0CB925158AD5FB3D083BDFE350E5D93B326'
	checksumType64 = 'sha1'
	silentArgs     = '/S'
	validExitCodes = @(0)
} Install-ChocolateyInstallPackage @packageArgs

Remove-Item -Force -EA 0 -Path $toolsDir\*.exe
```

The problem is:
`} Install-ChocolateyInstallPackage @packageArgs`

This should be:
}
Install-ChocolateyInstallPackage @packageArgs

It seems that the newline was dropped during internalization.

This causes this error:
```
ERROR: At C:\ProgramData\chocolatey\lib\multicommander\tools\chocolateyinstall.ps1:17 char:3
+ } Install-ChocolateyInstallPackage @packageArgs
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'Install-ChocolateyInstallPackage' in expression or statement.
The upgrade of multicommander was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\multicommander\tools\chocolateyinstall.ps1'.
 See log for details.

```

**Comment by TheCakeIsNaOH** [comment]
Huh, that is new. It looks like it is because the script has unix LF endings, instead of the PowerShell standard CRLF line endings. 
I've added a workaround, does https://github.com/TheCakeIsNaOH/choco-remixer/commit/4711899818a7cdac6ad4e8be7ae455d8d25a18c2 work for you?

**Comment by GertVanderstukken** [comment]
Yes, that works, but I guess it has an "impact" on all packages?
Maybe better to check for an LF that's not a CRLF

**Comment by TheCakeIsNaOH** [comment]
> Yes, that works, but I guess it has an "impact" on all packages?

Should just be a formatting issue in the worst case, I think it should be ok as is.
