### ISSUE TITLE
Modifying config file for x64 only

### ISSUE THREAD

**Issue by rmusick** [TheCakeIsNaOH/choco-remixer#29]
Hi,  I am going through some config files trying to set the the internalizer for x64 only.  For  some packages, I don't even see an option for it so I add the following to the line:
  <architecture>x64</architecture>
When I run the internalizer gain, it still downloads and packs both x64 and x32 versions.  Is there a way to fix this?

**Comment by TheCakeIsNaOH** [comment]
The `<architecture>` sets the available architecture(s) inside the package script. It is not intended to be used to select that only one architecture should be internalized. 

It is currently only used for packages that are internalized through `Convert-InstallChocolateyPackage`, packages that use other functions have the download hard-coded as a part of the function. 

Internalizing only one architecture is not a feature I am planning to add.
