### ISSUE TITLE
Troubles getting started

### ISSUE THREAD

**Issue by QuimaxW** [TheCakeIsNaOH/choco-remixer#3]
I'm trying to get this running for the first time. Choco is installed (already using it...). Have the repository cloned into D:\choco-remixer-master

Set-ExecutionPolicy Bypass
Import-Module .\choco-remixer.psm1
I have config.xml (modified), template.xml, and repo-check.xml in that folder, along with 7zip.install.21.7.nupkg and gimp.2.10.30.nupkg (which are also in the from folder below...) I've only modified config.xml with:
```
	<!-- Local directory where packages are searched for -->
	<searchDir>D:\chocopackages\from</searchDir>
	<!-- Local directory where the internalization actually happens -->
	<workDir>D:\chocopackages\in</workDir>
```
When I run "Invoke-InternalizeChocoPkg" this is the output:
```
Get-RemixerConfig : Cannot bind argument to parameter 'Path' because it is an empty string.
At D:\choco-remixer-master\choco-remixer\public\Invoke-InternalizeChocoPkg.ps1:26 char:5
+     . Get-RemixerConfig -parameterSetName $PSCmdlet.ParameterSetName
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-RemixerConfig], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-RemixerConfig
```

I have no clue what I'm missing here.

**Comment by TheCakeIsNaOH** [comment]
@QuimaxW It looks like the error output is not ideal there, so I've just pushed a commit to hopefully improve it. Poking around, it looks like the path resolution was not ideal, so I've added another commit to hopefully improve that. It also includes information in the [setup section of the readme](https://github.com/TheCakeIsNaOH/choco-remixer#setup).

Can you run `git pull`, re-import the module (if it is already imported, requires `-force` to reimport), and try running this again?

**Comment by QuimaxW** [comment]
@TheCakeIsNaOH  - Thank you! Whatever you changed seems to have done the trick. The couple of test packages seem to have built now. Now off to learn more...

**Comment by TheCakeIsNaOH** [comment]
Perfect.
