### ISSUE TITLE
Version is new, id unknown

### ISSUE THREAD

**Issue by Basti2244** [TheCakeIsNaOH/choco-remixer#5]
Hello,

I am getting the following error for two packages and i was wondering why the error occurs. 

```
WARNUNG: greenshot 1.2.10.6 is new, id unknown
WARNUNG: winmerge 2.16.20 is new, id unknown
```

I have the repo-check feature activated and in my repo-check.xml is a list of different programs.
There a programs like googlechrome which needs to be internalized and tools like winmerge or git which may already ready for offline use.

Google Chrome is working as expected, also Git or for example KeePass were just downloaded and pushed to a Nexus repository.
But for "greenshot" and "winmerge" it get the errors.

I would expect that these tools are downloaded, checked and pushed to the repository as the other. 
I found some code like "is already internal coming from chocolatey.org", but this seems to be not true in this condition case.
In the working directory are the nupkg files of these tools, so the download process works fine. But they are not pushed to the nexus repository.

Would be great to get some feedback.
Thanks in advance.

Best regards

**Comment by TheCakeIsNaOH** [comment]
@Basti2244 all packages need to be added individually. That warning is just telling you that these packages need to be added before they can be internalized. See https://github.com/TheCakeIsNaOH/choco-remixer/blob/master/ADDING_PACKAGES.md

I've updated the message to be more descriptive, and I've just added those two packages, so this should be working for you once you pull the latest commits.
