### ISSUE TITLE
Invoke-downloadchocopkg require PowershellGet v3.0.0

### ISSUE THREAD

**Issue by sylvainlavoie** [TheCakeIsNaOH/choco-remixer#9]
PowershellGet 3.0.0 is still beta and cannot be installed

 Install-Module PowerShellGet -Force -AllowPrerelease
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:37

**Comment by TheCakeIsNaOH** [comment]
@hb9chm does the `Invoke-DownloadChocopPkg` require PowerShellGet 3.0.0, or would it be ok to reduce the required version?

**Comment by hb9chm** [comment]
PowerShellGet Version 3.0 Preview 12 or higher is needed, because of  the feature "Save-PSResource -AsNupkg"
(see https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-12-release/)

**Comment by hb9chm** [comment]
AllowPrerelase is not supported on the "preinstalled" powershellget module version 1.0.0.1

First upgrade to the lastest offical version (2.2.5)

install-module powershellget -force
(for upgrading from the 1.0.0.1 Version to 2.2.5)

Restart Powershell 

Powershellget 2.2.5 supports the allowprerelease parameter

install-module powershellget -allowprerelease -force

**Comment by TheCakeIsNaOH** [comment]
Ah, right, that is why there was the prerelease error. 

@sylvainlavoie You can either use the provided method to install the v3.0.0 beta of Powershellget, or alternatively if you are not intending to use the `Invoke-DownloadChocoPkg` command, then you should be able to locally change the required version to allow you to use the other parts without having to upgrade Powershellget.

**Comment by TheCakeIsNaOH** [comment]
I've refactored `Invoke-DownloadChocoPkg` to no longer require PowerShellGet
